packages:
    - backend
    - frontend
    - shared
    - frontend/universal
    - desktop
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
    - build
overrides:
    react: 19.2.3
    react-dom: 19.2.3
    browserslist@<4.28.7: 4.28.7
    multer@<2.3.0: 2.3.0
    qs@<6.16.0: 6.16.0
    baseline-browser-mapping@<2.11.0: 2.11.0
    esbuild@<=0.24.2: 0.25.12
    nanoid@<3.3.18: 3.3.18
    postcss@<=8.5.22: 8.5.25
    sharp@<0.35.4: 0.35.4
    socket.io-parser@>=4.0.0 <4.2.7: 4.2.7
    undici@>=7.0.0 <7.29.0: 7.29.0
    fast-uri@>=3.0.0 <3.1.6: 3.1.6
    js-yaml@>=4.0.0 <4.3.2: 4.3.2
    brace-expansion@<1.1.18: 1.1.18
    brace-expansion@>=5.0.0 <5.0.9: 5.0.9
    xcode>uuid: 11.1.1
    '@types/react': 19.2.18
allowBuilds:
    unrs-resolver: true
    '@nestjs/core': true
    '@parcel/watcher': true
    esbuild: true
    electron: true
    electron-winstaller: true
    msgpackr-extract: true
    protobufjs: false
    sharp: true
    '@scarf/scarf': false
patchedDependencies:
    expo-sqlite: patches/expo-sqlite.patch
