import assert from 'node:assert/strict';
import test from 'node:test';
import { getDatabase, readSetting, selectAccountDatabase } from '../src/data/database';
import { finishLegacyChoice, legacyProfileCount } from '../src/data/legacy-workspace';
import { openDatabaseAsync } from './sqlite-adapter';
test('accounts stay isolated and legacy transfer preserves the original without carrying another session’s sync state', async () => {
  const legacy = await getDatabase();
  await legacy.runAsync('INSERT INTO profiles VALUES (?,?,?)', 1, 'Korábbi profil', 1);
  await legacy.runAsync('INSERT INTO sources VALUES (?,?,?,?,?,?,?,?,?)', 'old-source', 1, 'json', '{"version":1,"events":[]}', 'Import', 'old', '2026-10-01', '2026-10-31', 0);
  await legacy.runAsync('INSERT INTO settings VALUES (?,?)', 'cloudSync', '{"deviceId":"another-account"}');
  await selectAccountDatabase('first');
  assert.equal(await legacyProfileCount('first'), 1);
  await finishLegacyChoice('first', false);
  assert.equal(await legacyProfileCount('first'), 0);
  assert.deepEqual(await (await getDatabase()).getAllAsync('SELECT * FROM profiles'), []);
  await selectAccountDatabase('second');
  assert.equal(await legacyProfileCount('second'), 1);
  await finishLegacyChoice('second', true);
  assert.equal((await (await getDatabase()).getFirstAsync<{ name: string }>('SELECT name FROM profiles'))?.name, 'Korábbi profil');
  assert.equal(await readSetting('cloudSync', null), null);
  assert.equal(await readSetting('accountOwner', ''), 'second');
  const original = await openDatabaseAsync('orarend.db');
  assert.equal((await original.getFirstAsync('SELECT name FROM profiles'))?.name, 'Korábbi profil');
  assert.equal((await original.getFirstAsync('SELECT value FROM settings WHERE key=?', 'cloudSync'))?.value, '{"deviceId":"another-account"}');
  await selectAccountDatabase('third');
  assert.equal(await legacyProfileCount('third'), 0);
  assert.deepEqual(await (await getDatabase()).getAllAsync('SELECT * FROM profiles'), []);
  await selectAccountDatabase('second');
  assert.equal((await (await getDatabase()).getFirstAsync<{ name: string }>('SELECT name FROM profiles'))?.name, 'Korábbi profil');
});
